# Generated by Django 5.2.3 on 2025-06-19 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_count', models.IntegerField(default=0)),
                ('assignee', models.CharField(blank=True, max_length=128)),
                ('issue_type', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=128)),
                ('timestamp', models.DateTimeField()),
                ('resource', models.CharField(max_length=128)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.case')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
