version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      # use SQLite inside the container
      DATABASE_URL: sqlite:///app/db.sqlite3
      API_URL:     ${API_URL}
      SECRET_KEY:  ${SECRET_KEY}
      DEBUG:       ${DEBUG}
    volumes:
      # mount your backend dir to /app inside the container
      - ./backend:/app
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    env_file:
      - .env
    environment:
      # have Streamlit point at the backend
      API_URL: ${API_URL}
    volumes:
      # mount your Streamlit app dir to /app
      - ./streamlit_app:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
