# docker-compose.yml
version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    # override DATABASE_URL to use SQLite
    environment:
      DATABASE_URL: sqlite:///app/db.sqlite3
      API_URL:   ${API_URL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG:     ${DEBUG}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: streamlit_app/Dockerfile
    env_file:
      - .env
    environment:
      API_URL: ${API_URL}    # still http://backend:8000
    volumes:
      - ./streamlit_app:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
